### ISSUE TITLE
Version 1.0 milestone checklist (TODO)

### ISSUE THREAD

**Issue by rnd-ash** [rnd-ash/OpenVehicleDiag#18]
- [x] Automated KWP/UDS Scan for DTC codes
- [x] Grabbing part number over KWP for ECU identification
- [x] Fix broken OBD implementation (Still only over ISO-TP)
- [x] Complete all UDS SID implementations
- [x] Add support for Global diag requests for KWP2000 (Seems to apply to only MB Interior CAN devices)
- [x] Modify JSON format to be more similar to ODX (Categorize functions by "Adjustments", "Actuation", "Functions", and "Reading"
- [x] Add full beta version of SocketCAN

**Comment by andresv** [comment]
I like the work you are doing. Could you also format everything with `cargo fmt`, currently variable and method names are sometimes in snake_case sometimes in CamelCase. It will look more rusty after `cargo fmt`.
Keep up the good work!
