### ISSUE TITLE
[Checklist] Version 1.1

### ISSUE THREAD

**Issue by rnd-ash** [rnd-ash/OpenVehicleDiag#29]
# Checklist for Version 1.1

- [ ] Add support for BMW's .PRG parsing to JSON (WIP INPA branch)
- [ ] Add dynamic window resizing (#21)
- [ ] Update ICED GUI, including tooltips for certain functions
